### PR TITLE
Jhiszpanski/feature/missing projection err

### PR DESCRIPTION
**Pull request by hipek**
This change is [Reviewable](https://reviewable.io/reviews/nowthisnews/estore/1)

### CODE REVIEW

**Comment by tehAnswer** [comment]
Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/estore/1)*

**Comment by tehAnswer** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/estore/1#-:-KXANuZl6_srmTQAr5p0:bnfp4nl)*

**Comment by ImmaculatePine** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/estore/1#-:-KXAOzq_uztfB8Eu2tPV:bnfp4nl)*

**Comment by bilus** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nowthisnews/estore/1#-:-KXAUUaLN6zNe0lUr7Ou:bnfp4nl)*

**Pull request merged**
